//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("DatabaseModel", "FK_Episode_Series", "Series", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(MyShows.Core.Series), "Episode", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MyShows.Core.Episode), true)]
[assembly: EdmRelationshipAttribute("DatabaseModel", "FK_Subtitles_Episode", "Episode", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(MyShows.Core.Episode), "Subtitle", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MyShows.Core.Subtitles), true)]
[assembly: EdmRelationshipAttribute("DatabaseModel", "FK_Torrent_Episode", "Episode", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(MyShows.Core.Episode), "Torrent", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MyShows.Core.Torrent), true)]
[assembly: EdmRelationshipAttribute("DatabaseModel", "FK_Series_Profile", "Profile", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(MyShows.Core.Profile), "Series", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MyShows.Core.Series), true)]

#endregion

namespace MyShows.Core
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class DatabaseEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new DatabaseEntities object using the connection string found in the 'DatabaseEntities' section of the application configuration file.
        /// </summary>
        public DatabaseEntities() : base("name=DatabaseEntities", "DatabaseEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DatabaseEntities object.
        /// </summary>
        public DatabaseEntities(string connectionString) : base(connectionString, "DatabaseEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DatabaseEntities object.
        /// </summary>
        public DatabaseEntities(EntityConnection connection) : base(connection, "DatabaseEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Episode> Episodes
        {
            get
            {
                if ((_Episodes == null))
                {
                    _Episodes = base.CreateObjectSet<Episode>("Episodes");
                }
                return _Episodes;
            }
        }
        private ObjectSet<Episode> _Episodes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Profile> Profiles
        {
            get
            {
                if ((_Profiles == null))
                {
                    _Profiles = base.CreateObjectSet<Profile>("Profiles");
                }
                return _Profiles;
            }
        }
        private ObjectSet<Profile> _Profiles;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Series> Series
        {
            get
            {
                if ((_Series == null))
                {
                    _Series = base.CreateObjectSet<Series>("Series");
                }
                return _Series;
            }
        }
        private ObjectSet<Series> _Series;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Subtitles> Subtitles
        {
            get
            {
                if ((_Subtitles == null))
                {
                    _Subtitles = base.CreateObjectSet<Subtitles>("Subtitles");
                }
                return _Subtitles;
            }
        }
        private ObjectSet<Subtitles> _Subtitles;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Torrent> Torrents
        {
            get
            {
                if ((_Torrents == null))
                {
                    _Torrents = base.CreateObjectSet<Torrent>("Torrents");
                }
                return _Torrents;
            }
        }
        private ObjectSet<Torrent> _Torrents;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Episodes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToEpisodes(Episode episode)
        {
            base.AddObject("Episodes", episode);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Profiles EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToProfiles(Profile profile)
        {
            base.AddObject("Profiles", profile);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Series EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSeries(Series series)
        {
            base.AddObject("Series", series);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Subtitles EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSubtitles(Subtitles subtitles)
        {
            base.AddObject("Subtitles", subtitles);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Torrents EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTorrents(Torrent torrent)
        {
            base.AddObject("Torrents", torrent);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DatabaseModel", Name="Episode")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Episode : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Episode object.
        /// </summary>
        /// <param name="episodeId">Initial value of the EpisodeId property.</param>
        /// <param name="title">Initial value of the Title property.</param>
        /// <param name="number">Initial value of the Number property.</param>
        /// <param name="season">Initial value of the Season property.</param>
        /// <param name="seriesId">Initial value of the SeriesId property.</param>
        /// <param name="watched">Initial value of the Watched property.</param>
        /// <param name="lastUpdate">Initial value of the LastUpdate property.</param>
        /// <param name="airDate">Initial value of the AirDate property.</param>
        public static Episode CreateEpisode(global::System.Int64 episodeId, global::System.String title, global::System.Int32 number, global::System.Int32 season, global::System.Int64 seriesId, global::System.Boolean watched, global::System.DateTime lastUpdate, global::System.DateTime airDate)
        {
            Episode episode = new Episode();
            episode.EpisodeId = episodeId;
            episode.Title = title;
            episode.Number = number;
            episode.Season = season;
            episode.SeriesId = seriesId;
            episode.Watched = watched;
            episode.LastUpdate = lastUpdate;
            episode.AirDate = airDate;
            return episode;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 EpisodeId
        {
            get
            {
                return _EpisodeId;
            }
            set
            {
                if (_EpisodeId != value)
                {
                    OnEpisodeIdChanging(value);
                    ReportPropertyChanging("EpisodeId");
                    _EpisodeId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("EpisodeId");
                    OnEpisodeIdChanged();
                }
            }
        }
        private global::System.Int64 _EpisodeId;
        partial void OnEpisodeIdChanging(global::System.Int64 value);
        partial void OnEpisodeIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Number
        {
            get
            {
                return _Number;
            }
            set
            {
                OnNumberChanging(value);
                ReportPropertyChanging("Number");
                _Number = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Number");
                OnNumberChanged();
            }
        }
        private global::System.Int32 _Number;
        partial void OnNumberChanging(global::System.Int32 value);
        partial void OnNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Season
        {
            get
            {
                return _Season;
            }
            set
            {
                OnSeasonChanging(value);
                ReportPropertyChanging("Season");
                _Season = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Season");
                OnSeasonChanged();
            }
        }
        private global::System.Int32 _Season;
        partial void OnSeasonChanging(global::System.Int32 value);
        partial void OnSeasonChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 SeriesId
        {
            get
            {
                return _SeriesId;
            }
            set
            {
                OnSeriesIdChanging(value);
                ReportPropertyChanging("SeriesId");
                _SeriesId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SeriesId");
                OnSeriesIdChanged();
            }
        }
        private global::System.Int64 _SeriesId;
        partial void OnSeriesIdChanging(global::System.Int64 value);
        partial void OnSeriesIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Watched
        {
            get
            {
                return _Watched;
            }
            set
            {
                OnWatchedChanging(value);
                ReportPropertyChanging("Watched");
                _Watched = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Watched");
                OnWatchedChanged();
            }
        }
        private global::System.Boolean _Watched;
        partial void OnWatchedChanging(global::System.Boolean value);
        partial void OnWatchedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime LastUpdate
        {
            get
            {
                return _LastUpdate;
            }
            set
            {
                OnLastUpdateChanging(value);
                ReportPropertyChanging("LastUpdate");
                _LastUpdate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastUpdate");
                OnLastUpdateChanged();
            }
        }
        private global::System.DateTime _LastUpdate;
        partial void OnLastUpdateChanging(global::System.DateTime value);
        partial void OnLastUpdateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime AirDate
        {
            get
            {
                return _AirDate;
            }
            set
            {
                OnAirDateChanging(value);
                ReportPropertyChanging("AirDate");
                _AirDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AirDate");
                OnAirDateChanged();
            }
        }
        private global::System.DateTime _AirDate;
        partial void OnAirDateChanging(global::System.DateTime value);
        partial void OnAirDateChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DatabaseModel", "FK_Episode_Series", "Series")]
        public Series Series
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Series>("DatabaseModel.FK_Episode_Series", "Series").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Series>("DatabaseModel.FK_Episode_Series", "Series").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Series> SeriesReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Series>("DatabaseModel.FK_Episode_Series", "Series");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Series>("DatabaseModel.FK_Episode_Series", "Series", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DatabaseModel", "FK_Subtitles_Episode", "Subtitle")]
        public EntityCollection<Subtitles> Subtitles
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Subtitles>("DatabaseModel.FK_Subtitles_Episode", "Subtitle");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Subtitles>("DatabaseModel.FK_Subtitles_Episode", "Subtitle", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DatabaseModel", "FK_Torrent_Episode", "Torrent")]
        public EntityCollection<Torrent> Torrents
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Torrent>("DatabaseModel.FK_Torrent_Episode", "Torrent");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Torrent>("DatabaseModel.FK_Torrent_Episode", "Torrent", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DatabaseModel", Name="Profile")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Profile : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Profile object.
        /// </summary>
        /// <param name="profileId">Initial value of the ProfileId property.</param>
        /// <param name="login">Initial value of the Login property.</param>
        /// <param name="userId">Initial value of the UserId property.</param>
        /// <param name="password">Initial value of the Password property.</param>
        public static Profile CreateProfile(global::System.Int64 profileId, global::System.String login, global::System.Int32 userId, global::System.String password)
        {
            Profile profile = new Profile();
            profile.ProfileId = profileId;
            profile.Login = login;
            profile.UserId = userId;
            profile.Password = password;
            return profile;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ProfileId
        {
            get
            {
                return _ProfileId;
            }
            set
            {
                if (_ProfileId != value)
                {
                    OnProfileIdChanging(value);
                    ReportPropertyChanging("ProfileId");
                    _ProfileId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ProfileId");
                    OnProfileIdChanged();
                }
            }
        }
        private global::System.Int64 _ProfileId;
        partial void OnProfileIdChanging(global::System.Int64 value);
        partial void OnProfileIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Login
        {
            get
            {
                return _Login;
            }
            set
            {
                OnLoginChanging(value);
                ReportPropertyChanging("Login");
                _Login = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Login");
                OnLoginChanged();
            }
        }
        private global::System.String _Login;
        partial void OnLoginChanging(global::System.String value);
        partial void OnLoginChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                OnUserIdChanging(value);
                ReportPropertyChanging("UserId");
                _UserId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserId");
                OnUserIdChanged();
            }
        }
        private global::System.Int32 _UserId;
        partial void OnUserIdChanging(global::System.Int32 value);
        partial void OnUserIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DatabaseModel", "FK_Series_Profile", "Series")]
        public EntityCollection<Series> Series
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Series>("DatabaseModel.FK_Series_Profile", "Series");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Series>("DatabaseModel.FK_Series_Profile", "Series", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DatabaseModel", Name="Series")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Series : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Series object.
        /// </summary>
        /// <param name="seriesId">Initial value of the SeriesId property.</param>
        /// <param name="title">Initial value of the Title property.</param>
        /// <param name="profileId">Initial value of the ProfileId property.</param>
        public static Series CreateSeries(global::System.Int64 seriesId, global::System.String title, global::System.Int64 profileId)
        {
            Series series = new Series();
            series.SeriesId = seriesId;
            series.Title = title;
            series.ProfileId = profileId;
            return series;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 SeriesId
        {
            get
            {
                return _SeriesId;
            }
            set
            {
                if (_SeriesId != value)
                {
                    OnSeriesIdChanging(value);
                    ReportPropertyChanging("SeriesId");
                    _SeriesId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("SeriesId");
                    OnSeriesIdChanged();
                }
            }
        }
        private global::System.Int64 _SeriesId;
        partial void OnSeriesIdChanging(global::System.Int64 value);
        partial void OnSeriesIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ProfileId
        {
            get
            {
                return _ProfileId;
            }
            set
            {
                OnProfileIdChanging(value);
                ReportPropertyChanging("ProfileId");
                _ProfileId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ProfileId");
                OnProfileIdChanged();
            }
        }
        private global::System.Int64 _ProfileId;
        partial void OnProfileIdChanging(global::System.Int64 value);
        partial void OnProfileIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] Image
        {
            get
            {
                return StructuralObject.GetValidValue(_Image);
            }
            set
            {
                OnImageChanging(value);
                ReportPropertyChanging("Image");
                _Image = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Image");
                OnImageChanged();
            }
        }
        private global::System.Byte[] _Image;
        partial void OnImageChanging(global::System.Byte[] value);
        partial void OnImageChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DatabaseModel", "FK_Episode_Series", "Episode")]
        public EntityCollection<Episode> Episodes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Episode>("DatabaseModel.FK_Episode_Series", "Episode");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Episode>("DatabaseModel.FK_Episode_Series", "Episode", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DatabaseModel", "FK_Series_Profile", "Profile")]
        public Profile Profile
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Profile>("DatabaseModel.FK_Series_Profile", "Profile").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Profile>("DatabaseModel.FK_Series_Profile", "Profile").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Profile> ProfileReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Profile>("DatabaseModel.FK_Series_Profile", "Profile");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Profile>("DatabaseModel.FK_Series_Profile", "Profile", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DatabaseModel", Name="Subtitles")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Subtitles : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Subtitles object.
        /// </summary>
        /// <param name="subtitlesId">Initial value of the SubtitlesId property.</param>
        /// <param name="title">Initial value of the Title property.</param>
        /// <param name="episodeId">Initial value of the EpisodeId property.</param>
        /// <param name="file">Initial value of the File property.</param>
        public static Subtitles CreateSubtitles(global::System.Int64 subtitlesId, global::System.String title, global::System.Int64 episodeId, global::System.Byte[] file)
        {
            Subtitles subtitles = new Subtitles();
            subtitles.SubtitlesId = subtitlesId;
            subtitles.Title = title;
            subtitles.EpisodeId = episodeId;
            subtitles.File = file;
            return subtitles;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 SubtitlesId
        {
            get
            {
                return _SubtitlesId;
            }
            set
            {
                if (_SubtitlesId != value)
                {
                    OnSubtitlesIdChanging(value);
                    ReportPropertyChanging("SubtitlesId");
                    _SubtitlesId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("SubtitlesId");
                    OnSubtitlesIdChanged();
                }
            }
        }
        private global::System.Int64 _SubtitlesId;
        partial void OnSubtitlesIdChanging(global::System.Int64 value);
        partial void OnSubtitlesIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 EpisodeId
        {
            get
            {
                return _EpisodeId;
            }
            set
            {
                OnEpisodeIdChanging(value);
                ReportPropertyChanging("EpisodeId");
                _EpisodeId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EpisodeId");
                OnEpisodeIdChanged();
            }
        }
        private global::System.Int64 _EpisodeId;
        partial void OnEpisodeIdChanging(global::System.Int64 value);
        partial void OnEpisodeIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte[] File
        {
            get
            {
                return StructuralObject.GetValidValue(_File);
            }
            set
            {
                OnFileChanging(value);
                ReportPropertyChanging("File");
                _File = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("File");
                OnFileChanged();
            }
        }
        private global::System.Byte[] _File;
        partial void OnFileChanging(global::System.Byte[] value);
        partial void OnFileChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DatabaseModel", "FK_Subtitles_Episode", "Episode")]
        public Episode Episode
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Episode>("DatabaseModel.FK_Subtitles_Episode", "Episode").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Episode>("DatabaseModel.FK_Subtitles_Episode", "Episode").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Episode> EpisodeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Episode>("DatabaseModel.FK_Subtitles_Episode", "Episode");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Episode>("DatabaseModel.FK_Subtitles_Episode", "Episode", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DatabaseModel", Name="Torrent")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Torrent : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Torrent object.
        /// </summary>
        /// <param name="torrentId">Initial value of the TorrentId property.</param>
        /// <param name="title">Initial value of the Title property.</param>
        /// <param name="episodeId">Initial value of the EpisodeId property.</param>
        public static Torrent CreateTorrent(global::System.Int64 torrentId, global::System.String title, global::System.Int64 episodeId)
        {
            Torrent torrent = new Torrent();
            torrent.TorrentId = torrentId;
            torrent.Title = title;
            torrent.EpisodeId = episodeId;
            return torrent;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 TorrentId
        {
            get
            {
                return _TorrentId;
            }
            set
            {
                if (_TorrentId != value)
                {
                    OnTorrentIdChanging(value);
                    ReportPropertyChanging("TorrentId");
                    _TorrentId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("TorrentId");
                    OnTorrentIdChanged();
                }
            }
        }
        private global::System.Int64 _TorrentId;
        partial void OnTorrentIdChanging(global::System.Int64 value);
        partial void OnTorrentIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] File
        {
            get
            {
                return StructuralObject.GetValidValue(_File);
            }
            set
            {
                OnFileChanging(value);
                ReportPropertyChanging("File");
                _File = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("File");
                OnFileChanged();
            }
        }
        private global::System.Byte[] _File;
        partial void OnFileChanging(global::System.Byte[] value);
        partial void OnFileChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Magnet
        {
            get
            {
                return _Magnet;
            }
            set
            {
                OnMagnetChanging(value);
                ReportPropertyChanging("Magnet");
                _Magnet = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Magnet");
                OnMagnetChanged();
            }
        }
        private global::System.String _Magnet;
        partial void OnMagnetChanging(global::System.String value);
        partial void OnMagnetChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 EpisodeId
        {
            get
            {
                return _EpisodeId;
            }
            set
            {
                OnEpisodeIdChanging(value);
                ReportPropertyChanging("EpisodeId");
                _EpisodeId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EpisodeId");
                OnEpisodeIdChanged();
            }
        }
        private global::System.Int64 _EpisodeId;
        partial void OnEpisodeIdChanging(global::System.Int64 value);
        partial void OnEpisodeIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Seed
        {
            get
            {
                return _Seed;
            }
            set
            {
                OnSeedChanging(value);
                ReportPropertyChanging("Seed");
                _Seed = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Seed");
                OnSeedChanged();
            }
        }
        private Nullable<global::System.Int32> _Seed;
        partial void OnSeedChanging(Nullable<global::System.Int32> value);
        partial void OnSeedChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DatabaseModel", "FK_Torrent_Episode", "Episode")]
        public Episode Episode
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Episode>("DatabaseModel.FK_Torrent_Episode", "Episode").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Episode>("DatabaseModel.FK_Torrent_Episode", "Episode").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Episode> EpisodeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Episode>("DatabaseModel.FK_Torrent_Episode", "Episode");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Episode>("DatabaseModel.FK_Torrent_Episode", "Episode", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
